services:
  - type: web
    name: full-stack-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
